stages:

  model_train:
    cmd: python src/models/train_model.py
    deps:
    - src/models/dataframe_test.csv
    - src/models/train_model.py

  deploy_model:
    cmd: python app.py
    deps:
    - models/model_rf.sav
    - models/scaler.sav
    - templates/index.html
    - static